ESTUDENT/ESTUDENT.Web/Areas/Administration/Controllers/ExamController.cs
using ESTUDENT.Models;
using ESTUDENT.Services;
using ESTUDENT.Web.Controllers;
using Microsoft.AspNetCore.Mvc;
//using System;
//using System.Collections.Generic;
//using System.Linq;
//using System.Text;
//using System.Threading.Tasks;

namespace ESTUDENT.Web.Areas.Administration.Controllers
{
    [Area("Administration")]
    [Route("Administration/[controller]/[action]/{id?}")]
    public class ExamController : BaseController
    {
        #region Dependency injection
        /// <summary>
        /// Get Main Service
        /// </summary>
        private IService service;
        #endregion

        #region Constructor
        /// <summary>
        /// Default constructor
        /// </summary>
        /// <param name="service"></param>
        public ExamController(IService service)
        {
                this.service = service;
        }
        #endregion


        #region Actions/Functions
        /// <summary>
        /// Get All Exams
        /// </summary>
        /// <returns></returns>
        public IActionResult Exams()
        {

            // List<ExamModel> result = service.ReadAllExams();
            //List<StudentStudentExamExamModel> result2 = service.ReadAllCancelledExamsByStudentId(1);
            //return View(result);

            return View();
        }


        /// <summary>
        /// Get All Rows
        /// </summary>
        /// <returns></returns>
        public IActionResult Rows(int pageNumber, int rowsPerPage, string search)
        {
            List<ExamModel> result = service.TableSearch(pageNumber, rowsPerPage, search);

            return View(result);
        }


        /// <summary>
        /// Get All Exams
        /// </summary>
        /// <returns></returns>
        public IActionResult Edit()
        {

            return View();
        }


        /// <summary>
        /// Get All active Exams from StudentExam table 
        /// </summary>
        /// <returns></returns>
        public IActionResult ActiveExams() {

            List<StudentStudentExamExamModel> result = service.ReadAllActiveExams();
            return View(result);
        }


        /// <summary>
        /// Get All registered Exams from StudentExam table 
        /// </summary>
        /// <returns></returns>

        public IActionResult RegisteredExams()
        {

            List<StudentStudentExamExamModel> result = service.ReadAllRegisteredExams();
            return View(result);
        }

        #endregion
    }
}

ESTUDENT/ESTUDENT.Web/Areas/Administration/Controllers/StudentController.cs
using Microsoft.AspNetCore.Mvc;
using ESTUDENT.Models;
using ESTUDENT.Services;
using ESTUDENT.Web.Controllers;

namespace ESTUDENT.Web.Areas.Administration.Controllers
{

    [Area("Administration")]
    [Route("Administration/[controller]/[action]/{id?}")]
    public class StudentController : BaseController
    {
        

        #region Dependency injection
        /// <summary>
        /// Get Main Service
        /// </summary>
        private IService service;
        #endregion


        #region Constructor
        /// <summary>
        /// Default constructor
        /// </summary>
        /// <param name="service"></param>
        public StudentController(IService service)
        {
            this.service = service;
        }
        #endregion


        #region Actions/Functions

        public IActionResult Students()
        {
           // List<StudentModel> result = service.ReadAllStudents();
           // return View(result);
            return View();
        }

        public IActionResult Rows(int pageNumber, int rowsPerPage, string search)
        {
            List<StudentModel> result = service.TableSearchStudents(pageNumber, rowsPerPage, search);
            return View(result);
        }

        /// <summary>
        /// Load student method
        /// </summary>
        /// <returns></returns>
        public IActionResult Create() {

            return View();
        }


        /// <summary>
        /// Create student method
        /// </summary>
        /// <returns></returns>
        [HttpPost]
        public IActionResult Create(StudentModel model)
        {

            if (!ModelState.IsValid) {

                TempData["Response"] = false;
                TempData["ResponseMessage"] = "Neuspesno kreiran Student";
                return View(model);
            }
            try
            {
               var result =  service.CreateStudent(model);
                if (result != null)
                {
                    TempData["Response"] = true;
                    TempData["ResponseMessage"] = "Uspesno kreiran Student";
                }
                else{
                    TempData["Response"] = false;
                    TempData["ResponseMessage"] = "Neuspesno kreiran Student";
                }
               return View(model);
            }
            catch (Exception ex) {

                Console.WriteLine(ex.Message);
                return View(model);
            }

            return View();
        }

        /// <summary>
        /// Retrive the data from specific student by its id
        /// </summary>
        /// <returns></returns>
        public IActionResult Update(int id)
        {
            StudentModel model = service.ReadOneStudent(id);
            return View(model);
        }


        /// <summary>
        /// Create student method
        /// </summary>
        /// <returns></returns>
        [HttpPost]
        public IActionResult Update(StudentModel model)
        {

            if (!ModelState.IsValid)
            {

                TempData["Response"] = false;
                TempData["ResponseMessage"] = "Neuspesno update-ovan Student";
                return View(model);
            }
            try
            {
                service.UpdateStudent(model);
                TempData["Response"] = true;
                TempData["ResponseMessage"] = "Uspesno update-ovan Student";
                return View(model);

            }
            catch (Exception ex)
            {
                TempData["Response"] = false;
                TempData["ResponseMessage"] = "Neuspesno update-ovan Student";
                Console.WriteLine(ex.Message);
                return View(model);
            }

         
        }

        #endregion
    }
}

ESTUDENT/ESTUDENT.Web/Controllers/BaseController.cs
using Microsoft.AspNetCore.Localization;
using Microsoft.AspNetCore.Mvc;

namespace ESTUDENT.Web.Controllers
{
    public class BaseController : Controller
    {

        #region Culture management

        /// <summary>
        ///  Culture management - post method
        /// </summary>
        /// <param name="culture"></param>
        /// <param name="returnUrl"></param>
        /// <returns></returns>
        public IActionResult CultureManagement(string culture, string returnUrl) {

            Response.Cookies.Append(CookieRequestCultureProvider.DefaultCookieName, CookieRequestCultureProvider.MakeCookieValue(new RequestCulture(culture)),
                new CookieOptions { Expires = DateTimeOffset.Now.AddDays(30) });

            return LocalRedirect(returnUrl); 
        }


        /// <summary>
        /// Set culture management
        /// </summary>
        /// <param name="culture"></param>
        /// <returns></returns>
        public void SetCultureManagement(string culture)
        {
            Response.Cookies.Append(CookieRequestCultureProvider.DefaultCookieName, CookieRequestCultureProvider.MakeCookieValue(new RequestCulture(culture)),
                new CookieOptions { Expires = DateTimeOffset.Now.AddDays(30) });
        }

        #endregion Culture management

    }
}

ESTUDENT/ESTUDENT.Web/Views/Shared/CultureDropdown.cshtml
@inject IHtmlLocalizer<CultureDropdown> localizer
@inject Microsoft.Extensions.Options.IOptions<Microsoft.AspNetCore.Builder.RequestLocalizationOptions> localizationOptions



@{
	var culture = Context.Features.Get<Microsoft.AspNetCore.Localization.IRequestCultureFeature>();
	var cultureList = localizationOptions.Value.SupportedUICultures.Select(x => new SelectListItem { Value = x.Name, Text = localizer.GetString(x.Name) }).ToList();
	var returnUrl = string.IsNullOrWhiteSpace(Context.Request.Path) ? "~/" : $"~{Context.Request.Path.Value}{Context.Request.QueryString}";

}
<div class="dropdown">
  <a class="btn btn-secondary dropdown-toggle" href="#" role="button" id="dropdownMenuLink" data-bs-toggle="dropdown" aria-expanded="false">
    @culture.RequestCulture.UICulture.DisplayName
  </a>
  <ul class="dropdown-menu" aria-labelledby="dropdownMenuLink">
        @foreach (var item in cultureList)
        {
            <li><a class="dropdown-item" asp-area="" asp-controller="Base" asp-action="CultureManagement" asp-route-culture="@item.Value" 
                asp-route-returnUrl="@returnUrl" style="text-decoration: none !important;">@item.Text</a></li>        
        }

  </ul>
</div>

ESTUDENT/ESTUDENT.Web/Views/Shared/Footer.cshtml
 <footer class="footer py-4  ">
        <div class="container-fluid">
          <div class="row align-items-center justify-content-lg-between">
            <div class="col-lg-6 mb-lg-0 mb-4">
              <div class="copyright text-center text-sm text-muted text-lg-start">
                © <script>
                  document.write(new Date().getFullYear())
                </script>,
                made with <i class="fa fa-heart"></i> by
                <a href="https://www.creative-tim.com" class="font-weight-bold" target="_blank">Creative Tim</a>
                for a better web.
              </div>
            </div>
            <div class="col-lg-6">
              <ul class="nav nav-footer justify-content-center justify-content-lg-end">
                <li class="nav-item">
                  <a href="https://www.creative-tim.com" class="nav-link text-muted" target="_blank">Creative Tim</a>
                </li>
                <li class="nav-item">
                  <a href="https://www.creative-tim.com/presentation" class="nav-link text-muted" target="_blank">About Us</a>
                </li>
                <li class="nav-item">
                  <a href="https://www.creative-tim.com/blog" class="nav-link text-muted" target="_blank">Blog</a>
                </li>
                <li class="nav-item">
                  <a href="https://www.creative-tim.com/license" class="nav-link pe-0 text-muted" target="_blank">License</a>
                </li>
              </ul>
            </div>
          </div>
        </div>
      </footer>

ESTUDENT/ESTUDENT.Web/Views/Shared/Navbar.cshtml
 <!-- Navbar -->
   
    <nav class="navbar navbar-main navbar-expand-lg px-0 mx-4 shadow-none border-radius-xl" id="navbarBlur" navbar-scroll="true">
        
        <div class="container-fluid py-1 px-3">
        <nav aria-label="breadcrumb">
          <ol class="breadcrumb bg-transparent mb-0 pb-0 pt-1 px-0 me-sm-6 me-5">
            <li class="breadcrumb-item text-sm"><a class="opacity-5 text-dark" href="javascript:;">Pages</a></li>
            <li class="breadcrumb-item text-sm text-dark active" aria-current="page">Dashboard</li>
          </ol>
          <h6 class="font-weight-bolder mb-0">Dashboard</h6>
        </nav>
        <div class="collapse navbar-collapse mt-sm-0 mt-2 me-md-0 me-sm-4" id="navbar">

          <div class="ms-md-auto pe-md-3 d-flex align-items-center">
            <div class="input-group input-group-outline">
              <label class="form-label">Type here...</label>
              <input type="text" class="form-control" id="search">
            </div>
          </div>
          <ul class="navbar-nav  justify-content-end">
              
            <li class="nav-item d-flex align-items-center">
              <a href="javascript:;" class="nav-link text-body font-weight-bold px-0">
                <i class="fa fa-user me-sm-1"></i>
                <span class="d-sm-inline d-none">Sign In</span>
              </a>
            </li>
            <li class="nav-item d-xl-none ps-3 d-flex align-items-center">
              <a href="javascript:;" class="nav-link text-body p-0" id="iconNavbarSidenav">
                <div class="sidenav-toggler-inner">
                  <i class="sidenav-toggler-line"></i>
                  <i class="sidenav-toggler-line"></i>
                  <i class="sidenav-toggler-line"></i>
                </div>
              </a>
            </li>
            <li class="nav-item px-3 d-flex align-items-center">
              <a href="javascript:;" class="nav-link text-body p-0">
                <i class="fa fa-cog fixed-plugin-button-nav cursor-pointer"></i>
              </a>
            </li>
            <li class="nav-item dropdown pe-2 d-flex align-items-center">
              <a href="javascript:;" class="nav-link text-body p-0" id="dropdownMenuButton" data-bs-toggle="dropdown" aria-expanded="false">
                <i class="fa fa-bell cursor-pointer"></i>
              </a>
              <ul class="dropdown-menu  dropdown-menu-end  px-2 py-3 me-sm-n4" aria-labelledby="dropdownMenuButton">
                <li class="mb-2">
                  <a class="dropdown-item border-radius-md" href="javascript:;">
                    <div class="d-flex py-1">
                      <div class="my-auto">
                        <img src="~/img/team-2.jpg" class="avatar avatar-sm  me-3 ">
                      </div>
                      <div class="d-flex flex-column justify-content-center">
                        <h6 class="text-sm font-weight-normal mb-1">
                          <span class="font-weight-bold">New message</span> from Laur
                        </h6>
                        <p class="text-xs text-secondary mb-0">
                          <i class="fa fa-clock me-1"></i>
                          13 minutes ago
                        </p>
                      </div>
                    </div>
                  </a>
                </li>
                <li class="mb-2">
                  <a class="dropdown-item border-radius-md" href="javascript:;">
                    <div class="d-flex py-1">
                      <div class="my-auto">
                        <img src="~/img/small-logos/logo-spotify.svg" class="avatar avatar-sm bg-gradient-dark  me-3 ">
                      </div>
                      <div class="d-flex flex-column justify-content-center">
                        <h6 class="text-sm font-weight-normal mb-1">
                          <span class="font-weight-bold">New album</span> by Travis Scott
                        </h6>
                        <p class="text-xs text-secondary mb-0">
                          <i class="fa fa-clock me-1"></i>
                          1 day
                        </p>
                      </div>
                    </div>
                  </a>
                </li>
                <li>
                  <a class="dropdown-item border-radius-md" href="javascript:;">
                    <div class="d-flex py-1">
                      <div class="avatar avatar-sm bg-gradient-secondary  me-3  my-auto">
                        <svg width="12px" height="12px" viewBox="0 0 43 36" version="1.1" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink">
                          <title>credit-card</title>
                          <g stroke="none" stroke-width="1" fill="none" fill-rule="evenodd">
                            <g transform="translate(-2169.000000, -745.000000)" fill="#FFFFFF" fill-rule="nonzero">
                              <g transform="translate(1716.000000, 291.000000)">
                                <g transform="translate(453.000000, 454.000000)">
                                  <path class="color-background" d="M43,10.7482083 L43,3.58333333 C43,1.60354167 41.3964583,0 39.4166667,0 L3.58333333,0 C1.60354167,0 0,1.60354167 0,3.58333333 L0,10.7482083 L43,10.7482083 Z" opacity="0.593633743"></path>
                                  <path class="color-background" d="M0,16.125 L0,32.25 C0,34.2297917 1.60354167,35.8333333 3.58333333,35.8333333 L39.4166667,35.8333333 C41.3964583,35.8333333 43,34.2297917 43,32.25 L43,16.125 L0,16.125 Z M19.7083333,26.875 L7.16666667,26.875 L7.16666667,23.2916667 L19.7083333,23.2916667 L19.7083333,26.875 Z M35.8333333,26.875 L28.6666667,26.875 L28.6666667,23.2916667 L35.8333333,23.2916667 L35.8333333,26.875 Z"></path>
                                </g>
                              </g>
                            </g>
                          </g>
                        </svg>
                      </div>
                      <div class="d-flex flex-column justify-content-center">
                        <h6 class="text-sm font-weight-normal mb-1">
                          Payment successfully completed
                        </h6>
                        <p class="text-xs text-secondary mb-0">
                          <i class="fa fa-clock me-1"></i>
                          2 days
                        </p>
                      </div>
                    </div>
                  </a>
                </li>
              </ul>
            </li>
            <partial name="CultureDropdown"/>
          </ul>
        </div>
      </div>
    </nav>

ESTUDENT/ESTUDENT.Web/Views/Shared/Scripts.cshtml
 <!--   Core JS Files   -->
  <script src="~/js/core/popper.min.js"></script>
  <script src="~/js/core/bootstrap.min.js"></script>
  <script src="~/js/plugins/perfect-scrollbar.min.js"></script>
  <script src="~/js/plugins/smooth-scrollbar.min.js"></script>
  <script src="~/js/plugins/chartjs.min.js"></script>
  <script src="~/lib/jquery/dist/jquery.js"></script>

    <script>
    var win = navigator.platform.indexOf('Win') > -1;
    if (win && document.querySelector('#sidenav-scrollbar')) {
      var options = {
        damping: '0.5'
      }
      Scrollbar.init(document.querySelector('#sidenav-scrollbar'), options);
    }
  </script>
  <!-- Github buttons -->
  <script async defer src="~/js/plugins/github-buttons.js"></script>
  <!-- Control Center for Material Dashboard: parallax effects, scripts for the example pages etc -->
  <script src="~/js/material-dashboard.min.js?v=3.0.1"></script>

ESTUDENT/ESTUDENT.Web/Views/Shared/Settings.cshtml
<div class="fixed-plugin">
    <a class="fixed-plugin-button text-dark position-fixed px-3 py-2">
      <i class="material-icons py-2">settings</i>
    </a>
    <div class="card shadow-lg">
      <div class="card-header pb-0 pt-3">
        <div class="float-start">
          <h5 class="mt-3 mb-0">Material UI Configurator</h5>
          <p>See our dashboard options.</p>
        </div>
        <div class="float-end mt-4">
          <button class="btn btn-link text-dark p-0 fixed-plugin-close-button">
            <i class="material-icons">clear</i>
          </button>
        </div>
        <!-- End Toggle Button -->
      </div>
      <hr class="horizontal dark my-1">
      <div class="card-body pt-sm-3 pt-0">
        <!-- Sidebar Backgrounds -->
        <div>
          <h6 class="mb-0">Sidebar Colors</h6>
        </div>
        <a href="javascript:void(0)" class="switch-trigger background-color">
          <div class="badge-colors my-2 text-start">
            <span class="badge filter bg-gradient-primary active" data-color="primary" onclick="sidebarColor(this)"></span>
            <span class="badge filter bg-gradient-dark" data-color="dark" onclick="sidebarColor(this)"></span>
            <span class="badge filter bg-gradient-info" data-color="info" onclick="sidebarColor(this)"></span>
            <span class="badge filter bg-gradient-success" data-color="success" onclick="sidebarColor(this)"></span>
            <span class="badge filter bg-gradient-warning" data-color="warning" onclick="sidebarColor(this)"></span>
            <span class="badge filter bg-gradient-danger" data-color="danger" onclick="sidebarColor(this)"></span>
          </div>
        </a>
        <!-- Sidenav Type -->
        <div class="mt-3">
          <h6 class="mb-0">Sidenav Type</h6>
          <p class="text-sm">Choose between 2 different sidenav types.</p>
        </div>
        <div class="d-flex">
          <button class="btn bg-gradient-dark px-3 mb-2 active" data-class="bg-gradient-dark" onclick="sidebarType(this)">Dark</button>
          <button class="btn bg-gradient-dark px-3 mb-2 ms-2" data-class="bg-transparent" onclick="sidebarType(this)">Transparent</button>
          <button class="btn bg-gradient-dark px-3 mb-2 ms-2" data-class="bg-white" onclick="sidebarType(this)">White</button>
        </div>
        <p class="text-sm d-xl-none d-block mt-2">You can change the sidenav type just on desktop view.</p>
        <!-- Navbar Fixed -->
        <div class="mt-3 d-flex">
          <h6 class="mb-0">Navbar Fixed</h6>
          <div class="form-check form-switch ps-0 ms-auto my-auto">
            <input class="form-check-input mt-1 ms-auto" type="checkbox" id="navbarFixed" onclick="navbarFixed(this)">
          </div>
        </div>
        <hr class="horizontal dark my-3">
        <div class="mt-2 d-flex">
          <h6 class="mb-0">Light / Dark</h6>
          <div class="form-check form-switch ps-0 ms-auto my-auto">
            <input class="form-check-input mt-1 ms-auto" type="checkbox" id="dark-version" onclick="darkMode(this)">
          </div>
        </div>
        <hr class="horizontal dark my-sm-4">
        <a class="btn bg-gradient-info w-100" href="https://www.creative-tim.com/product/material-dashboard">Free Download</a>
        <a class="btn btn-outline-dark w-100" href="https://www.creative-tim.com/learning-lab/bootstrap/overview/material-dashboard">View documentation</a>
        <div class="w-100 text-center">
          <a class="github-button" href="https://github.com/creativetimofficial/material-dashboard" data-icon="octicon-star" data-size="large" data-show-count="true" aria-label="Star creativetimofficial/material-dashboard on GitHub">Star</a>
          <h6 class="mt-3">Thank you for sharing!</h6>
          <a href="https://twitter.com/intent/tweet?text=Check%20Material%20UI%20Dashboard%20made%20by%20%40CreativeTim%20%23webdesign%20%23dashboard%20%23bootstrap5&amp;url=https%3A%2F%2Fwww.creative-tim.com%2Fproduct%2Fsoft-ui-dashboard" class="btn btn-dark mb-0 me-2" target="_blank">
            <i class="fab fa-twitter me-1" aria-hidden="true"></i> Tweet
          </a>
          <a href="https://www.facebook.com/sharer/sharer.php?u=https://www.creative-tim.com/product/material-dashboard" class="btn btn-dark mb-0 me-2" target="_blank">
            <i class="fab fa-facebook-square me-1" aria-hidden="true"></i> Share
          </a>
        </div>
      </div>
    </div>
  </div>

ESTUDENT/ESTUDENT.Web/Views/Shared/Sidenavbar.cshtml
<aside class="sidenav navbar navbar-vertical navbar-expand-xs border-0 border-radius-xl my-3 fixed-start ms-3   bg-gradient-dark" id="sidenav-main">
    <div class="sidenav-header">
      <i class="fas fa-times p-3 cursor-pointer text-white opacity-5 position-absolute end-0 top-0 d-none d-xl-none" aria-hidden="true" id="iconSidenav"></i>
      <a class="navbar-brand m-0" asp-action="Index" target="_blank">
        <img src="~/img/logo-ct.png" class="navbar-brand-img h-100" alt="main_logo">
        <span class="ms-1 font-weight-bold text-white">E-STUDENT</span>
      </a>
    </div>
    <hr class="horizontal light mt-0 mb-2">
     <div class="collapse navbar-collapse  w-auto " id="sidenav-collapse-main">
      <ul class="navbar-nav">
        <li class="nav-item">
          <a class="nav-link text-white " asp-action="Index" asp-controller="Home" asp-area="" >
          
            <span class="nav-link-text ms-1">Profile</span>
          </a>
        </li>
        <li class="nav-item">
          <a class="nav-link text-white "  asp-action="Exams" asp-controller="Exam" asp-area="Administration">
           
            <span class="nav-link-text ms-1">Exams</span>
          </a>
       
        <li class="nav-item">
          <a class="nav-link text-white " asp-action="ActiveExams" asp-controller="Exam" asp-area="Administration">
           
            <span class="nav-link-text ms-1">Active Exams</span>
          </a>
        </li>
          <li class="nav-item">
          <a class="nav-link text-white " asp-action="RegisteredExams" asp-controller="Exam" asp-area="Administration">
           
            <span class="nav-link-text ms-1">Registered Exams</span>
          </a>
        </li>
          <li class="nav-item">
          <a class="nav-link text-white " asp-action="Students" asp-controller="Student" asp-area="Administration">
           
            <span class="nav-link-text ms-1">Students</span>
          </a>
        </li>
      </ul>
    </div>
    <div class="sidenav-footer position-absolute w-100 bottom-0 ">
      <div class="mx-3">
        <a class="btn bg-gradient-primary mt-4 w-100" href="https://www.creative-tim.com/product/material-dashboard-pro?ref=sidebarfree" type="button">Upgrade to pro</a>
      </div>
    </div>
</aside>   

ESTUDENT/ESTUDENT.Web/Views/Shared/Styles.cshtml
 
 <link rel="apple-touch-icon" sizes="76x76" href="~/img/apple-icon.png">
  <link rel="icon" type="image/png" href="~/img/favicon.png">
<!--     Fonts and icons     -->
  <link rel="stylesheet" href="~/google-fonts/Roboto.css" />
 
  <!-- Nucleo Icons -->
  <link href="~/css/nucleo-icons.css" rel="stylesheet" />
  <link href="~/css/nucleo-svg.css" rel="stylesheet" />
  
  
  <!-- Font Awesome Icons -->
  <script src="~/js/plugins/font-awsome-external-link.js"></script>
 
  <!-- Material Icons -->
  <link href="~/google-fonts/Material.css" rel="stylesheet">
  
  <!-- CSS Files -->
  <link id="pagestyle" href="~/css/material-dashboard.css?v=3.0.1" rel="stylesheet" />

ESTUDENT/ESTUDENT.Web/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">

<head>

  <meta charset="utf-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    
  <title>
        @ViewData["Title"] - E-STUDENT-portal.Web
    </title>

     <partial name="Styles" />
     @await RenderSectionAsync("Styles", required: false);

</head>

<body class="g-sidenav-show  bg-gray-200">
  
  <partial name="Sidenavbar" />

  <main class="main-content position-relative max-height-vh-100 h-100 border-radius-lg ">
   
    <div class="container-fluid py-4">
        <partial name="Navbar" />
       
    @RenderBody() @*Ovde ce se ucitavati nase parcijalne stranice To smo iskoppirali iz naseg inicijalnog file-a*@  

    <partial name="Footer"/>

    </div>

  </main>
  
     
     @*<partial name="Settings" />*@


</body>

     <partial name="Scripts" />
     @await RenderSectionAsync("Scripts", required: false)

</html